env:
  # MCP Server Configuration
  - name: MCP_SERVERS
    value: kubernetes,grafana
  - name: MCP_KUBERNETES_URL
    value: http://kubernetes-mcp-server.kubernetes-mcp-server.svc.cluster.local:8080/mcp
  - name: MCP_KUBERNETES_ENABLED
    value: "true"
  - name: MCP_KUBERNETES_TRANSPORT
    value: http

  # Grafana MCP Server Configuration
  - name: MCP_GRAFANA_URL
    value: http://my-release-grafana-mcp.mcp-grafana.svc.cluster.local:8000/sse
  - name: MCP_GRAFANA_ENABLED
    value: "true"
  - name: MCP_GRAFANA_TRANSPORT
    value: sse

  # Agent's model
  - name: EIN_AGENT_MODEL
    value: "gemini/gemini-3-flash-preview"

  # Alertmanager Configuration
  - name: ALERTMANAGER_URL
    value: http://alertmanager.cos.svc.cluster.local:9093

juju:
  - secret-id: d4nsqv7mp25c77vcjq90
